# Eardogger config file
# Use the `--config <FILE>` option to pick a config location. If omitted,
# we try to find eardogger.toml in the current working directory.
#
# All the settings here are mandatory unless otherwise stated, and the
# app will fail to start if the config file isn't valid. Running the
# app binary with the `--status` option is an easy way to check the config
# before upgrading the server to a new version.
#
# All of the file/directory settings can be either relative or absolute paths.
# Relative paths are resolved relative to the config file's location.

# Whether we're running in production or not. Affects verbosity of 500 errors.
production = false

# How many OS worker threads the Tokio runtime will use. By default,
# tokio will use "the number of cores available to the system," which
# *it's possible* your web host will hate. Must be > 0.
runtime_threads = 4

# How many DB reader threads to cap out at. Must be > 0. This is _in addition_
# to the Tokio runtime threads. Also, there's always one additional thread for
# the DB writer. For best results, ensure (runtime_threads + reader_threads + 1)
# is ≤ the number of virtual CPU cores in your system.
reader_threads = 2

# Whether to check the integrity of database migrations on every startup.
# If migrations are behind or corrupt, the app will exit instead of
# potentially messing up user data.
validate_migrations = true

# The site's own public-facing base URL.
public_url = "http://localhost:3000"
db_file = "dev.db"
assets_dir = "public"
key_file = "cookie_key.bin"

[log]
# An EnvFilter string, as described in the tracing-subscriber docs:
# https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/filter/struct.EnvFilter.html
filter = "info"
# Whether to log to stdout. In local dev that's your terminal, and in a
# PaaS it's probably some log collector service. But in mod_fcgid, it
# goes to Apache's MAIN ErrorLog file (NOT your vhost's ErrorLog),
# which you almost certainly do not want. So use log.file instead.
stdout = true

# The whole log.file section is optional. If present, we write rolling
# daily "<name>.<timestamp>.log" files to <directory>, keeping <days>
# days worth and deleting any older ones.
[log.file]
# The directory to use for log files.
directory = "logs"
# The log file prefix. Files will have names like <name>.<timestamp>.log.
name = "eardogger"
# How many days of logs to keep. Excess logs are auto-deleted.
days = 5

# Choose ONE group of mode settings, either http or fcgi.
[mode.http]
# The port to listen on.
port = 3000

# or, alternately:
# [mode.fcgi]
# The maximum number of connections to serve at once. Above this number,
# new connections will have to wait and will get higher latency.
# max_connections = 50
